# Generated by Django 5.0.4 on 2024-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_emp1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp1',
        ),
    ]
