# Generated by Django 5.0.4 on 2024-05-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_emp12_delete_emp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp12',
            name='emp_id',
        ),
    ]
