# Generated by Django 5.0.4 on 2024-05-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_emp12_emp_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp12',
            new_name='Emp123',
        ),
    ]
