# Generated by Django 5.0.4 on 2024-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='actual_testimonial',
            new_name='testimonial',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(upload_to='Testimonial/'),
        ),
    ]
